#!/usr/bin/env python3
"""Genera MASTER_FRONTEND_RUNTIME_GAP_MATRIX.csv — auditoría maestra frontend+runtime.

AUDIT ONLY: este script no toca código de producto. Reproduce la matriz
machine-readable a partir de la definición canónica de filas (misma fuente que
MASTER_FRONTEND_RUNTIME_GAP_MATRIX.md).

Uso:  python3 generate_gap_matrix.py
Salida: MASTER_FRONTEND_RUNTIME_GAP_MATRIX.csv (en esta carpeta)
"""
import csv
import os

COLUMNS = [
    "capability_id", "capability", "domain", "process", "source_requirement", "source_spec",
    "expected_role", "expected_company", "expected_bu", "expected_permission",
    "backend_route", "backend_state", "frontend_route", "frontend_component",
    "frontend_repo_state", "nav_entry", "discoverable", "deployed",
    "runtime_visible", "runtime_functional", "persistence", "refresh", "relogin",
    "negative_auth", "e2e", "screenshot", "network_evidence",
    "existing_finding", "primary_product_status", "secondary_gaps", "severity",
    "root_cause", "owner_decision", "remediation_dependency",
    "proposed_remediation_group", "evidence_ref",
]

B = "BLOCKED_AUTH"  # fila pendiente de verificación autenticada (no es estado primario)

def row(**kw):
    missing = [c for c in COLUMNS if c not in kw]
    assert not missing, f"faltan columnas: {missing} en {kw.get('capability_id')}"
    return [kw[c] for c in COLUMNS]

ROWS = [
    # ── Sesión ──────────────────────────────────────────────────────────────
    row(capability_id="CAP-SES-01", capability="Iniciar sesión / sesión con token", domain="sesion", process="—",
        source_requirement="docs/02 §3.1", source_spec="GA-REM-003", expected_role="todos", expected_company="efectiva",
        expected_bu="—", expected_permission="—", backend_route="POST /auth/login", backend_state="IMPLEMENTED",
        frontend_route="/login", frontend_component="LoginPage", frontend_repo_state="IMPLEMENTED", nav_entry="—",
        discoverable="sí", deployed="PRESENT", runtime_visible="sí (renderizado)", runtime_functional=B,
        persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="existente (E2E-01-01)", screenshot="AUDIT_001",
        network_evidence="probes 401 sin sesión", existing_finding="—", primary_product_status=B,
        secondary_gaps="riesgo R-44 (reconciliación de permisos) no verificado", severity="—", root_cause="—",
        owner_decision="—", remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="EVIDENCE §9"),

    row(capability_id="CAP-SES-02", capability="Cambio de contraseña", domain="sesion", process="—",
        source_requirement="GA-REM-012", source_spec="GA-REM-012", expected_role="todos", expected_company="efectiva",
        expected_bu="—", expected_permission="—", backend_route="POST /users/{id}/password", backend_state="IMPLEMENTED",
        frontend_route="/profile", frontend_component="ProfilePage", frontend_repo_state="IMPLEMENTED", nav_entry="menú perfil",
        discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B, persistence=B, refresh=B,
        relogin=B, negative_auth=B, e2e="—", screenshot="—", network_evidence="sonda 2026-09-04 (405 ruta existe)",
        existing_finding="—", primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—",
        owner_decision="—", remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="FINGERPRINT §2"),

    row(capability_id="CAP-SES-03", capability="Perfil de usuario (ver datos)", domain="sesion", process="—",
        source_requirement="docs/02 §3.1.4", source_spec="GA-REM-011", expected_role="todos", expected_company="efectiva",
        expected_bu="—", expected_permission="—", backend_route="GET /me", backend_state="IMPLEMENTED",
        frontend_route="/profile", frontend_component="ProfilePage", frontend_repo_state="IMPLEMENTED", nav_entry="menú perfil",
        discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B, persistence=B, refresh=B,
        relogin=B, negative_auth=B, e2e="—", screenshot="—", network_evidence="401 /me", existing_finding="R-66 (P3, cerrado)",
        primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—", owner_decision="—",
        remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth", evidence_ref="EVIDENCE §9"),

    row(capability_id="CAP-SES-04", capability="Contexto de empresa visible", domain="multiempresa", process="—",
        source_requirement="OD-11", source_spec="docs/02 §3.1.4", expected_role="todos", expected_company="efectiva",
        expected_bu="—", expected_permission="—", backend_route="GET /me (campos)", backend_state="IMPLEMENTED",
        frontend_route="Header + badges", frontend_component="Header / Dashboard / Profile", frontend_repo_state="IMPLEMENTED",
        nav_entry="—", discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B,
        persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="—", screenshot="—",
        network_evidence="company_name en código y bundle", existing_finding="—", primary_product_status=B,
        secondary_gaps="—", severity="—", root_cause="—", owner_decision="—", remediation_dependency="—",
        proposed_remediation_group="G0-verificacion-auth", evidence_ref="EVIDENCE §10"),

    row(capability_id="CAP-SES-05", capability="Selector de empresa (actor global)", domain="multiempresa", process="—",
        source_requirement="docs/02 §3.1.4 («futuro»)", source_spec="OD-14 + PHASE_9_PREFLIGHT",
        expected_role="Super Admin", expected_company="global", expected_bu="—", expected_permission="masters:read",
        backend_route="GET /masters/companies + POST /switch-company", backend_state="IMPLEMENTED",
        frontend_route="Header dropdown", frontend_component="company.store.ts + Header.tsx", frontend_repo_state="IMPLEMENTED",
        nav_entry="header", discoverable="solo en cabecera; condicionado", deployed="PRESENT (ambos bundles)",
        runtime_visible="sí (estático)", runtime_functional=B, persistence=B, refresh=B, relogin=B, negative_auth="sí (super_admin)",
        e2e="—", screenshot="AUDIT_001 (pre-login)", network_evidence="/switch-company 405 (POST)",
        existing_finding="R-48/R-54 (cerrados) · R-127/OD-18", primary_product_status="IMPLEMENTED_BUT_NOT_EXPOSED",
        secondary_gaps="render solo si company_name presente; sólo is_super_admin (por diseño OD-14); fetch con catch silencioso; verificación autenticada bloqueada",
        severity="P2", root_cause="exposición incompleta del selector", owner_decision="BU-D07 pendiente (comercial vs operativo)",
        remediation_dependency="fase 9 T-040-23 / WAVE E", proposed_remediation_group="G4-exposicion-navegacion",
        evidence_ref="EVIDENCE §10"),

    # ── Administración ──────────────────────────────────────────────────────
    row(capability_id="CAP-ADM-01", capability="Catálogo de empresas (listado)", domain="multiempresa", process="—",
        source_requirement="docs/02 §3.2.1", source_spec="OD-18 + R-127", expected_role="admin", expected_company="control global",
        expected_bu="—", expected_permission="masters:read", backend_route="GET /masters/companies", backend_state="IMPLEMENTED",
        frontend_route="/masters/companies", frontend_component="MasterListPage", frontend_repo_state="IMPLEMENTED",
        nav_entry="maestros", discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B,
        persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="—", screenshot="—", network_evidence="401 desplegado",
        existing_finding="R-127 cerrado", primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—",
        owner_decision="—", remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="FINGERPRINT §4"),

    row(capability_id="CAP-ADM-02", capability="Administración de empresas (crear/editar metadatos)", domain="multiempresa", process="—",
        source_requirement="docs/02 §3.2.1", source_spec="R-124/AOD-06 + OD-18.b", expected_role="admin", expected_company="control global",
        expected_bu="—", expected_permission="masters:update", backend_route="PUT /masters/companies/{id}", backend_state="PARTIAL (escritura sap_config DEFERRED)",
        frontend_route="/masters/companies", frontend_component="MasterListPage", frontend_repo_state="PARTIAL",
        nav_entry="maestros", discoverable="parcial", deployed="PRESENT", runtime_visible="parcial", runtime_functional=B,
        persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="—", screenshot="—", network_evidence="—",
        existing_finding="R-124 · R-127.b DEFERRED", primary_product_status="OWNER_DECISION_REQUIRED",
        secondary_gaps="propiedad SAP vs local sin decidir; exposición de sap_config decidida (OD-18)", severity="P1",
        root_cause="expectativa no definida", owner_decision="AOD-06 (R-124)", remediation_dependency="WAVE D",
        proposed_remediation_group="G1-multiempresa", evidence_ref="EVIDENCE §11"),

    row(capability_id="CAP-ADM-03", capability="Unidades por empresa — habilitar/deshabilitar", domain="unidades", process="—",
        source_requirement="GA-REM-040 AC-H04", source_spec="T-040-21 + OD-16.b", expected_role="Administrador de Accesos / Super Admin",
        expected_company="efectiva", expected_bu="las 4", expected_permission="business_units:read+update",
        backend_route="GET /business-units · PATCH …/enable|disable", backend_state="IMPLEMENTED (fase 7, desplegado 401)",
        frontend_route="—", frontend_component="—", frontend_repo_state="MISSING (0 referencias)", nav_entry="—",
        discoverable="no", deployed="ABSENT", runtime_visible="no", runtime_functional="no (no existe UI)",
        persistence="—", refresh="—", relogin="—", negative_auth="backend sí", e2e="—", screenshot="—",
        network_evidence="401 desplegado", existing_finding="fase 9 FROZEN", primary_product_status="FRONTEND_MISSING",
        secondary_gaps="fase 9 congelada (autorización del propietario); backend completo", severity="P1",
        root_cause="frontend nunca construido", owner_decision="autorización fase 9", remediation_dependency="fase 9",
        proposed_remediation_group="G2-admin-empresa-BU", evidence_ref="EVIDENCE §11"),

    row(capability_id="CAP-ADM-04", capability="Unidades por usuario — conceder/revocar", domain="unidades", process="—",
        source_requirement="GA-REM-040 AC-H05", source_spec="T-040-22 + OD-15 + R-129", expected_role="Administrador de Accesos",
        expected_company="efectiva", expected_bu="las 4", expected_permission="business_units:create+delete",
        backend_route="GET …/grant-candidates · POST/DELETE /users/{id}/business-units", backend_state="IMPLEMENTED (desplegado 401)",
        frontend_route="—", frontend_component="—", frontend_repo_state="MISSING (0 referencias)", nav_entry="—",
        discoverable="no", deployed="ABSENT", runtime_visible="no", runtime_functional="no", persistence="—", refresh="—",
        relogin="—", negative_auth="backend sí", e2e="—", screenshot="—", network_evidence="401 desplegado",
        existing_finding="R-129 cerrado; fase 9 FROZEN", primary_product_status="FRONTEND_MISSING",
        secondary_gaps="interfaz podría usar R-129 sin users:read", severity="P1", root_cause="frontend nunca construido",
        owner_decision="autorización fase 9", remediation_dependency="fase 9", proposed_remediation_group="G3-admin-usuario-BU",
        evidence_ref="EVIDENCE §11"),

    row(capability_id="CAP-ADM-05", capability="Bandeja de clasificación pendiente", domain="unidades", process="—",
        source_requirement="GA-REM-040 AC-H07", source_spec="T-040-24 + OD-10.c", expected_role="Administrador de Accesos",
        expected_company="efectiva", expected_bu="pendiente", expected_permission="masters:update+corrections:correct",
        backend_route="GET /operations/pending-classification", backend_state="IMPLEMENTED (desplegado 401)",
        frontend_route="—", frontend_component="—", frontend_repo_state="MISSING", nav_entry="—", discoverable="no",
        deployed="ABSENT", runtime_visible="no", runtime_functional="no", persistence="—", refresh="—", relogin="—",
        negative_auth="backend sí", e2e="—", screenshot="—", network_evidence="401 desplegado",
        existing_finding="fase 9 FROZEN", primary_product_status="FRONTEND_MISSING",
        secondary_gaps="condicionada al diseño de fase 9", severity="P2", root_cause="frontend nunca construido",
        owner_decision="autorización fase 9", remediation_dependency="fase 9", proposed_remediation_group="G3-admin-usuario-BU",
        evidence_ref="EVIDENCE §11"),

    row(capability_id="CAP-ADM-06", capability="Navegación adaptada a permisos y unidades", domain="navegacion", process="—",
        source_requirement="docs/02 §3.1.3 + GA-REM-040 AC-H02/03", source_spec="T-040-23 + R-119/H360-F01",
        expected_role="todos", expected_company="efectiva", expected_bu="efectivas", expected_permission="según rol",
        backend_route="sesión (permissions + effective_business_units)", backend_state="IMPLEMENTED (fase 8)",
        frontend_route="navigationConfig.ts", frontend_component="Sidebar / MobileDrawer", frontend_repo_state="MISSING (menú estático)",
        nav_entry="—", discoverable="no (menú completo para todos)", deployed="ABSENT", runtime_visible="no",
        runtime_functional="no", persistence="—", refresh="—", relogin="—", negative_auth="backend sí", e2e="—",
        screenshot="—", network_evidence="0 hasPermission en frontend", existing_finding="R-98/R-119 abiertos; fase 9 FROZEN",
        primary_product_status="FRONTEND_MISSING", secondary_gaps="ProtectedRoute.roles es código muerto; el menú enseña puertas que el backend cierra",
        severity="P1", root_cause="frontend sin modelo de permisos", owner_decision="—",
        remediation_dependency="fase 9 + R-119", proposed_remediation_group="G5-rbac-navegacion", evidence_ref="EVIDENCE §14"),

    row(capability_id="CAP-ADM-07", capability="Estado «sin unidades» (zero-BU)", domain="navegacion", process="—",
        source_requirement="GA-REM-040 AC-H06", source_spec="T-040-23 + OD-09.c", expected_role="usuario sin unidades",
        expected_company="efectiva", expected_bu="[]", expected_permission="—", backend_route="(estado de sesión)",
        backend_state="IMPLEMENTED", frontend_route="—", frontend_component="—", frontend_repo_state="MISSING",
        nav_entry="—", discoverable="no", deployed="ABSENT", runtime_visible="no", runtime_functional="no",
        persistence="—", refresh="—", relogin="—", negative_auth="—", e2e="—", screenshot="—",
        network_evidence="—", existing_finding="H360-F02 (clase R-150)", primary_product_status="FRONTEND_MISSING",
        secondary_gaps="sin distinción denegación/vacío", severity="P2", root_cause="frontend nunca construido",
        owner_decision="—", remediation_dependency="fase 9", proposed_remediation_group="G5-rbac-navegacion",
        evidence_ref="EVIDENCE §15"),

    row(capability_id="CAP-ADM-08", capability="Gestión de usuarios (CRUD + desactivación)", domain="administracion", process="P-13",
        source_requirement="docs/02 §3.1.2", source_spec="GA-REM-002 AC13–16", expected_role="admin", expected_company="efectiva",
        expected_bu="—", expected_permission="users:*", backend_route="/users CRUD", backend_state="IMPLEMENTED",
        frontend_route="/users", frontend_component="UsersPage", frontend_repo_state="IMPLEMENTED", nav_entry="sí (settings)",
        discoverable="sí", deployed="PRESENT (generación 09-05)", runtime_visible="sí", runtime_functional=B,
        persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="P-13 (aislado)", screenshot="—",
        network_evidence="401 /users", existing_finding="R-122 vigente (columna Empresa)", primary_product_status=B,
        secondary_gaps="en runtime persiste «denegación = tabla vacía» (R-120 solo en local); columna Empresa ausente (R-122)",
        severity="P2", root_cause="—", owner_decision="—", remediation_dependency="R-122", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="EVIDENCE §15"),

    row(capability_id="CAP-ADM-09", capability="Roles y permisos (pantalla)", domain="administracion", process="P-13",
        source_requirement="docs/02 §3.1.3", source_spec="GA-REM-034", expected_role="admin", expected_company="efectiva",
        expected_bu="—", expected_permission="roles admin", backend_route="/roles + /roles/permissions-catalog", backend_state="IMPLEMENTED",
        frontend_route="/roles", frontend_component="RolesPage", frontend_repo_state="IMPLEMENTED", nav_entry="settings → usuarios y roles",
        discoverable="sí en local", deployed="ABSENT (ruta ausente del bundle servido)", runtime_visible="no",
        runtime_functional="no", persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B,
        e2e="P-13 (aislado)", screenshot="—", network_evidence="«/roles» 1 ref vs 7 (deployed vs local)",
        existing_finding="R-99", primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="el runtime sirve la generación 09-05; la pantalla existe desde 09-06", severity="P2",
        root_cause="artefacto congelado (R-99)", owner_decision="—", remediation_dependency="R-99 (despliegue)",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="FINGERPRINT §5"),

    row(capability_id="CAP-ADM-10", capability="Asignación de rol en formulario de usuario", domain="administracion", process="P-13",
        source_requirement="OD-13/OD-15", source_spec="GA-REM-034", expected_role="admin", expected_company="efectiva",
        expected_bu="—", expected_permission="users:update", backend_route="/users/{id}", backend_state="IMPLEMENTED",
        frontend_route="/users", frontend_component="UsersPage formulario", frontend_repo_state="IMPLEMENTED", nav_entry="sí",
        discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B, persistence=B, refresh=B,
        relogin=B, negative_auth=B, e2e="P-13", screenshot="—", network_evidence="—", existing_finding="—",
        primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—", owner_decision="—",
        remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth", evidence_ref="EVIDENCE §13"),

    # ── Unidades productivas ────────────────────────────────────────────────
    row(capability_id="CAP-BU-01", capability="Entradas productivas de las 4 unidades", domain="productivo", process="varios",
        source_requirement="OD-16.a", source_spec="docs/02 §3.4", expected_role="todos", expected_company="efectiva",
        expected_bu="efectivas", expected_permission="—", backend_route="rutas /poultry/*", backend_state="IMPLEMENTED",
        frontend_route="/poultry + /menu/:key", frontend_component="PoultryHub / ProcessStage", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí (Gestión Avícola)", discoverable="sí", deployed="PRESENT (/poultry ×30 en ambos bundles)",
        runtime_visible="sí (estático)", runtime_functional=B, persistence=B, refresh=B, relogin=B, negative_auth=B,
        e2e="p01–p06 (aislado)", screenshot="—", network_evidence="—", existing_finding="—", primary_product_status=B,
        secondary_gaps="diferenciación por unidad sin gating (CAP-ADM-06)", severity="P2", root_cause="—",
        owner_decision="—", remediation_dependency="CAP-ADM-06", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="EVIDENCE §16"),

    row(capability_id="CAP-BU-02", capability="Importación de abuelas — plan tipado (Progenitoras)", domain="productivo", process="P-01",
        source_requirement="docs/02 §3.4.1 · spec.md §4.4", source_spec="GA-REM-042/R-152", expected_role="Supervisor",
        expected_company="efectiva", expected_bu="grandparent", expected_permission="operations:create",
        backend_route="POST /operations (import_plan, BR-22)", backend_state="IMPLEMENTED (exige import_plan)",
        frontend_route="/operations/new", frontend_component="OperationFormPage (plan)", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí (poultry → grandparent)", discoverable="sí en local", deployed="ABSENT/DIVERGENT",
        runtime_visible="no (import_plan 0 en bundle)", runtime_functional="no — 400 BR-22 con la UI antigua",
        persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B, e2e="p01 actualizado (local)",
        screenshot="—", network_evidence="import_plan 0→1 (bundles)", existing_finding="R-99 + BR-22",
        primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="EN RUNTIME el flujo está roto: la UI 09-05 no envía el plan → 400 BR-22", severity="P1",
        root_cause="artefacto congelado", owner_decision="R-153/AOD-25 depende de R-152 (cerrado)",
        remediation_dependency="R-99", proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-BU-03", capability="Catálogo de incubadora (mortalidad/descarte)", domain="productivo", process="P-05",
        source_requirement="Bases p.10 · Rec. §12", source_spec="GA-REM-021-D/R-171", expected_role="operativos",
        expected_company="efectiva", expected_bu="hatchery", expected_permission="operations:create",
        backend_route="POST /operations (mortality/cull)", backend_state="IMPLEMENTED (AC-R161-16)", frontend_route="/poultry/hatchery",
        frontend_component="PoultryStage + processCatalog", frontend_repo_state="IMPLEMENTED", nav_entry="sí",
        discoverable="sí en local", deployed="ABSENT", runtime_visible="no", runtime_functional="no (etapa sin los dos tipos)",
        persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B, e2e="vitest 5/5 (local)",
        screenshot="—", network_evidence="—", existing_finding="R-171 cerrado (local)", primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="ui_only pendiente de despliegue", severity="P2", root_cause="artefacto congelado",
        owner_decision="—", remediation_dependency="R-99", proposed_remediation_group="G7-deploy-parity",
        evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-BU-04", capability="Creación automática del lote de abuelas", domain="productivo", process="P-01",
        source_requirement="docs/02 §3.4.2 · spec.md §4.4", source_spec="R-153/AOD-25", expected_role="sistema/producto",
        expected_company="efectiva", expected_bu="grandparent", expected_permission="—", backend_route="(no existe)",
        backend_state="MISSING (decisión pendiente)", frontend_route="—", frontend_component="—", frontend_repo_state="MISSING",
        nav_entry="—", discoverable="no", deployed="ABSENT", runtime_visible="no", runtime_functional="no",
        persistence="—", refresh="—", relogin="—", negative_auth="—", e2e="—", screenshot="—", network_evidence="—",
        existing_finding="AOD-25", primary_product_status="OWNER_DECISION_REQUIRED",
        secondary_gaps="qué es «completar»; código del lote; si puebla; convivencia con vía manual", severity="P3",
        root_cause="expectativa no definida", owner_decision="AOD-25", remediation_dependency="R-152 (cerrado)",
        proposed_remediation_group="G1-multiempresa", evidence_ref="EVIDENCE §17"),

    # ── Operativo ───────────────────────────────────────────────────────────
    row(capability_id="CAP-OPS-01", capability="Recepción de aves (P-01, flujo general)", domain="operativo", process="P-01",
        source_requirement="spec.md §4.4", source_spec="PROCESS-01", expected_role="Operador/Supervisor", expected_company="efectiva",
        expected_bu="—", expected_permission="operations:create", backend_route="POST /operations", backend_state="IMPLEMENTED",
        frontend_route="/operations/new", frontend_component="OperationFormPage", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí", discoverable="sí", deployed="PRESENT (09-05)", runtime_visible="sí", runtime_functional=B,
        persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="E2E-01 (aislado)", screenshot="—", network_evidence="—",
        existing_finding="—", primary_product_status=B, secondary_gaps="reproductoras rotas (CAP-OPS-02)", severity="—",
        root_cause="—", owner_decision="—", remediation_dependency="CAP-OPS-02", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-02", capability="Recepción de reproductoras — cuadre B01 y pesos B02", domain="operativo", process="P-01",
        source_requirement="Rec. §6 · RR-12/13 · BR-20", source_spec="GA-REM-021-B/037-B", expected_role="Supervisor",
        expected_company="efectiva", expected_bu="breeder", expected_permission="operations:create",
        backend_route="POST /operations (BR-20 exige recibidas+mortalidad+rechazo)", backend_state="IMPLEMENTED",
        frontend_route="/operations/new", frontend_component="OperationFormPage (B01/B02)", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí", discoverable="sí en local", deployed="ABSENT", runtime_visible="no", runtime_functional="no — 400 BR-20 con la UI antigua",
        persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B, e2e="tranche 7 (aislado)",
        screenshot="—", network_evidence="dead_on_arrival 0→1 (bundles)", existing_finding="R-99 + BR-20",
        primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="EN RUNTIME el flujo está roto: la UI 09-05 no declara los tres datos → 400 BR-20", severity="P1",
        root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-03", capability="Control diario de producción (P-02)", domain="operativo", process="P-02",
        source_requirement="spec.md §4.x", source_spec="PROCESS-02/GA-REM-005", expected_role="Operador", expected_company="efectiva",
        expected_bu="—", expected_permission="operations:create", backend_route="POST /operations", backend_state="IMPLEMENTED",
        frontend_route="/operations/new", frontend_component="OperationFormPage", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí", discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B, persistence=B,
        refresh=B, relogin=B, negative_auth=B, e2e="E2E-02 (aislado)", screenshot="—", network_evidence="—",
        existing_finding="—", primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—",
        owner_decision="—", remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-04", capability="Nacimiento en incubadora — sanos/débiles (B13) y conteo (R-170)", domain="operativo", process="P-05",
        source_requirement="Bases p.9 · BR-21", source_spec="GA-REM-005-C/021-C", expected_role="Encargado incubadora",
        expected_company="efectiva", expected_bu="hatchery", expected_permission="operations:create",
        backend_route="POST /operations (BR-21 exige sanos/débiles)", backend_state="IMPLEMENTED", frontend_route="/operations/new",
        frontend_component="OperationFormPage (birth)", frontend_repo_state="IMPLEMENTED", nav_entry="sí",
        discoverable="sí en local", deployed="ABSENT", runtime_visible="no", runtime_functional="no — 400 BR-21 con la UI antigua",
        persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B, e2e="tranche 8 (aislado)",
        screenshot="—", network_evidence="chicks_healthy 0→1 (bundles)", existing_finding="R-99 + BR-21",
        primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="EN RUNTIME el flujo está roto: la UI 09-05 no envía sanos/débiles y duplica el total → 400 BR-21",
        severity="P1", root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-05", capability="Consumo de agua (B05)", domain="operativo", process="P-02/P-06",
        source_requirement="Bases p.2/4/12 · RR-10/11", source_spec="GA-REM-021-A/R-13", expected_role="Operador",
        expected_company="efectiva", expected_bu="breeder+broiler", expected_permission="operations:create",
        backend_route="POST /operations (water_consumption, water_liters>0)", backend_state="IMPLEMENTED",
        frontend_route="/operations/new", frontend_component="OperationFormPage (water)", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí", discoverable="sí en local", deployed="PARCIAL (reporte agregaba)", runtime_visible="no (captura ausente)",
        runtime_functional="no", persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B,
        e2e="tranche 6 (aislado)", screenshot="—", network_evidence="water_liters 1→2 (bundles)", existing_finding="R-99",
        primary_product_status="DEPLOYMENT_STALE", secondary_gaps="captura local (72600f1) sin desplegar", severity="P2",
        root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-06", capability="Despacho — una sola fila fértil / cantidad > 0 (R-172/R-174)", domain="operativo", process="P-05",
        source_requirement="BR-02/BR-04", source_spec="GA-REM-005-E/F", expected_role="Operador incubadora",
        expected_company="efectiva", expected_bu="hatchery", expected_permission="operations:create",
        backend_route="POST /operations (dispatch)", backend_state="IMPLEMENTED (solo fértil; >0)",
        frontend_route="/operations/new", frontend_component="OperationFormPage (dispatch)", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí", discoverable="sí en local", deployed="ABSENT/DIVERGENT", runtime_visible="no",
        runtime_functional="probable 400 con tipos no fértiles", persistence="sí (local)", refresh="sí (local)", relogin="sí (local)",
        negative_auth=B, e2e="tranche 10 (aislado)", screenshot="—", network_evidence="commit 64dff76", existing_finding="R-99",
        primary_product_status="DEPLOYMENT_STALE", secondary_gaps="UI antigua permite tipos hoy rechazados por BR-02", severity="P2",
        root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-07", capability="Ciclo Revisión→Corrección→Aprobación (P-07)", domain="operativo", process="P-07",
        source_requirement="docs/12", source_spec="PROCESS-03/OD-17/OD-19", expected_role="Supervisor/Aprobador",
        expected_company="efectiva", expected_bu="—", expected_permission="review:*/approvals:*", backend_route="/review/* + /approvals/*",
        backend_state="IMPLEMENTED", frontend_route="/review/* + /approvals", frontend_component="ReviewCenter/Detail/CorrectionForm",
        frontend_repo_state="IMPLEMENTED", nav_entry="sí", discoverable="sí", deployed="PRESENT", runtime_visible="sí",
        runtime_functional=B, persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="E2E-03 (aislado)", screenshot="—",
        network_evidence="—", existing_finding="—", primary_product_status=B,
        secondary_gaps="envío explícito sin UI (CAP-OPS-08); R-181", severity="—", root_cause="—", owner_decision="—",
        remediation_dependency="CAP-OPS-08", proposed_remediation_group="G0-verificacion-auth", evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-08", capability="Envío/reenvío explícito a revisión (submit)", domain="operativo", process="P-07",
        source_requirement="docs/12 §2/§4 · OD-17.b", source_spec="R-135 (backend) + R-181 (nuevo)", expected_role="Operador/Supervisor",
        expected_company="efectiva", expected_bu="—", expected_permission="operations:update",
        backend_route="POST /operations/{id}/submit", backend_state="IMPLEMENTED (desplegado)", frontend_route="—",
        frontend_component="— (servicio sin llamadores)", frontend_repo_state="MISSING", nav_entry="—", discoverable="no",
        deployed="ABSENT", runtime_visible="no", runtime_functional="no (no existe control UI)", persistence="—", refresh="—",
        relogin="—", negative_auth="backend sí", e2e="E2E por API (proceso-03/p06/p14)", screenshot="—",
        network_evidence="«/submit» 0 refs en bundle; 1 def muerta en src", existing_finding="R-181 NUEVO",
        primary_product_status="FRONTEND_MISSING",
        secondary_gaps="el gesto «Operador reenvía» de docs/12 §2 no es ejecutable; los E2E lo suplen por API", severity="P2",
        root_cause="vertical UI nunca cableada", owner_decision="—", remediation_dependency="ninguna (backend listo)",
        proposed_remediation_group="G5-rbac-navegacion", evidence_ref="EVIDENCE §18"),

    row(capability_id="CAP-OPS-09", capability="Pantalla de reverso (solicitar/consultar)", domain="operativo", process="P-07",
        source_requirement="BR-16 · OD-19", source_spec="GA-REM-041/R-136", expected_role="Supervisor/Contraloría",
        expected_company="efectiva", expected_bu="según evento", expected_permission="reversals:*",
        backend_route="POST/GET /reversals", backend_state="IMPLEMENTED (desplegado 401)", frontend_route="—",
        frontend_component="—", frontend_repo_state="MISSING (0 referencias)", nav_entry="—", discoverable="no",
        deployed="ABSENT", runtime_visible="no", runtime_functional="no", persistence="—", refresh="—", relogin="—",
        negative_auth="backend sí", e2e="—", screenshot="—", network_evidence="401 desplegado",
        existing_finding="GA-REM-041 §10: fase 9 · R-136 evidencia: «frontend … fase 9»", primary_product_status="FRONTEND_MISSING",
        secondary_gaps="aplazada explícitamente a fase 9", severity="P2", root_cause="frontend nunca construido",
        owner_decision="—", remediation_dependency="fase 9", proposed_remediation_group="G6-reverso", evidence_ref="EVIDENCE §18"),

    row(capability_id="CAP-OPS-10", capability="Lotes (P-06)", domain="operativo", process="P-06",
        source_requirement="spec.md §4.x", source_spec="PROCESS-06/GA-REM-029/036", expected_role="Admin/Supervisor",
        expected_company="efectiva", expected_bu="—", expected_permission="lots:*", backend_route="/lots*", backend_state="IMPLEMENTED",
        frontend_route="/lots*", frontend_component="LotList/Detail/Form", frontend_repo_state="IMPLEMENTED", nav_entry="sí",
        discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B, persistence=B, refresh=B,
        relogin=B, negative_auth=B, e2e="P-06 (aislado)", screenshot="—", network_evidence="—", existing_finding="—",
        primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—", owner_decision="—",
        remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth", evidence_ref="EVIDENCE §17"),

    row(capability_id="CAP-OPS-11", capability="Evidencias (subir/descargar)", domain="operativo", process="P-07",
        source_requirement="Rec. §6 · docs/02 §7", source_spec="GA-REM-009", expected_role="operativos", expected_company="efectiva",
        expected_bu="—", expected_permission="evidence", backend_route="POST/GET evidences", backend_state="IMPLEMENTED (volumen R-52 pendiente)",
        frontend_route="/operations/:id", frontend_component="OperationDetailPage", frontend_repo_state="IMPLEMENTED",
        nav_entry="detalle", discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B,
        persistence=B, refresh=B, relogin=B, negative_auth=B, e2e="—", screenshot="—", network_evidence="—",
        existing_finding="R-52 vigente", primary_product_status=B,
        secondary_gaps="R-52: volumen compartido no montado — evidencias efímeras en el runtime", severity="P1",
        root_cause="—", owner_decision="—", remediation_dependency="R-52", proposed_remediation_group="G0-verificacion-auth",
        evidence_ref="EVIDENCE §19"),

    row(capability_id="CAP-OPS-12", capability="Dashboard / KPI", domain="operativo", process="P-15",
        source_requirement="docs/02 §3.5", source_spec="PROCESS-15", expected_role="todos", expected_company="efectiva",
        expected_bu="—", expected_permission="—", backend_route="GET /dashboard/*", backend_state="IMPLEMENTED",
        frontend_route="/ + /kpi", frontend_component="DashboardPage", frontend_repo_state="IMPLEMENTED", nav_entry="sí",
        discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B, persistence=B, refresh=B,
        relogin=B, negative_auth=B, e2e="P-15 (aislado)", screenshot="—", network_evidence="—", existing_finding="—",
        primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—", owner_decision="—",
        remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth", evidence_ref="EVIDENCE §19"),

    row(capability_id="CAP-OPS-13", capability="SAP — gestión de referencias/envíos", domain="integracion", process="P-08",
        source_requirement="docs/10", source_spec="OD-12/GA-REM-010", expected_role="Analista SAP", expected_company="efectiva",
        expected_bu="—", expected_permission="sap:*", backend_route="/sap/*", backend_state="PARTIAL (R-112: 8 rutas sin response_model)",
        frontend_route="/sap", frontend_component="SapManagerPage", frontend_repo_state="IMPLEMENTED", nav_entry="sí",
        discoverable="sí", deployed="PRESENT", runtime_visible="sí", runtime_functional=B, persistence=B, refresh=B,
        relogin=B, negative_auth=B, e2e="—", screenshot="—", network_evidence="—", existing_finding="R-112 · P-08 BLOCKED_EXTERNAL",
        primary_product_status=B, secondary_gaps="—", severity="—", root_cause="—", owner_decision="—",
        remediation_dependency="—", proposed_remediation_group="G0-verificacion-auth", evidence_ref="EVIDENCE §19"),

    # ── Maestros / auditoría / notificaciones ──────────────────────────────
    row(capability_id="CAP-MAS-01", capability="Gestión completa de maestros (19 + áreas)", domain="maestros", process="P-12",
        source_requirement="docs/02 §3.2", source_spec="GA-REM-033/R-90/91", expected_role="admin", expected_company="efectiva",
        expected_bu="—", expected_permission="masters:*", backend_route="/masters/* (20 entidades)", backend_state="IMPLEMENTED",
        frontend_route="/masters/*", frontend_component="MasterListPage (20)", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí", discoverable="sí", deployed="PARCIAL (/masters 30 refs vs 39)", runtime_visible="parcial",
        runtime_functional="no (7 nuevos + áreas ausentes)", persistence="sí (local)", refresh="sí (local)", relogin="sí (local)",
        negative_auth=B, e2e="P-12 (aislado)", screenshot="—", network_evidence="—", existing_finding="R-99",
        primary_product_status="DEPLOYMENT_STALE", secondary_gaps="siete maestros y áreas sin superficie en el runtime",
        severity="P2", root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §20"),

    row(capability_id="CAP-MAS-02", capability="Áreas (maestro administrable)", domain="maestros", process="P-12",
        source_requirement="GA-REM-039", source_spec="OD-08", expected_role="admin", expected_company="efectiva",
        expected_bu="—", expected_permission="masters:*", backend_route="/masters/areas", backend_state="IMPLEMENTED",
        frontend_route="/masters/areas", frontend_component="MasterListPage (areas)", frontend_repo_state="IMPLEMENTED",
        nav_entry="sí en local", discoverable="sí en local", deployed="ABSENT", runtime_visible="no", runtime_functional="no",
        persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B, e2e="—", screenshot="—",
        network_evidence="areas 2→3 (bundles)", existing_finding="R-99", primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="maestro creado 09-07 no desplegado", severity="P2", root_cause="artefacto congelado",
        owner_decision="—", remediation_dependency="R-99", proposed_remediation_group="G7-deploy-parity",
        evidence_ref="EVIDENCE §20"),

    row(capability_id="CAP-MAS-03", capability="Curvas de peso (carga de tabla + evaluación)", domain="maestros", process="P-03",
        source_requirement="OD-06 · R-96", source_spec="R-96/97 · GA-REM-037", expected_role="admin", expected_company="efectiva",
        expected_bu="—", expected_permission="masters:*", backend_route="/masters/genetic-lines/:id/weight-curves + service",
        backend_state="IMPLEMENTED", frontend_route="/masters/genetic-lines/:id/weight-curves",
        frontend_component="WeightCurvesPage", frontend_repo_state="IMPLEMENTED", nav_entry="sí en local", discoverable="sí en local",
        deployed="ABSENT", runtime_visible="no (/weight-curves 0→6)", runtime_functional="no", persistence="sí (local)",
        refresh="sí (local)", relogin="sí (local)", negative_auth=B, e2e="p03 (aislado)", screenshot="—",
        network_evidence="/weight-curves 0→6 (bundles)", existing_finding="R-99", primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="capacidad de carga local (09-06) no desplegada", severity="P2", root_cause="artefacto congelado",
        owner_decision="—", remediation_dependency="R-99", proposed_remediation_group="G7-deploy-parity",
        evidence_ref="EVIDENCE §20"),

    row(capability_id="CAP-AUD-01", capability="Auditoría — filtros reales y cobertura", domain="auditoria", process="P-09",
        source_requirement="docs/02 §3.11.2", source_spec="GA-REM-032/R-81/82/84", expected_role="Auditor", expected_company="efectiva",
        expected_bu="—", expected_permission="audit:read", backend_route="/audit/*", backend_state="IMPLEMENTED",
        frontend_route="/audit", frontend_component="AuditPage", frontend_repo_state="IMPLEMENTED", nav_entry="sí",
        discoverable="sí", deployed="DIVERGENT (generación 09-05)", runtime_visible="sí (versión antigua)",
        runtime_functional="no (pestañas que no filtraban)", persistence="sí (local)", refresh="sí (local)", relogin="sí (local)",
        negative_auth=B, e2e="—", screenshot="—", network_evidence="4386f87", existing_finding="R-99",
        primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="el runtime aún muestra los filtros que no filtraban (R-82 certificado técnicamente)", severity="P2",
        root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §20"),

    row(capability_id="CAP-NOT-01", capability="Notificaciones internas (campana/bandeja)", domain="notificaciones", process="P-14",
        source_requirement="OD-07 · docs/02 §3.14", source_spec="GA-REM-038/R-38", expected_role="todos", expected_company="efectiva",
        expected_bu="—", expected_permission="—", backend_route="/notifications/*", backend_state="IMPLEMENTED",
        frontend_route="/notifications (campana en header)", frontend_component="NotificationBell + service", frontend_repo_state="IMPLEMENTED",
        nav_entry="header", discoverable="sí en local", deployed="ABSENT", runtime_visible="no (/notifications 0→3)",
        runtime_functional="no", persistence="sí (local)", refresh="sí (local)", relogin="sí (local)", negative_auth=B,
        e2e="p14 (aislado)", screenshot="—", network_evidence="/notifications 0→3 (bundles)", existing_finding="R-99",
        primary_product_status="DEPLOYMENT_STALE", secondary_gaps="canal interno completo sin desplegar (P-14 certificado en aislado)",
        severity="P2", root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §20"),

    row(capability_id="CAP-ERR-01", capability="Estados de error distinguibles (denegación ≠ vacío)", domain="ux", process="—",
        source_requirement="R-120 · H360-F02", source_spec="GA-REM-002 AC16", expected_role="todos", expected_company="efectiva",
        expected_bu="—", expected_permission="—", backend_route="—", backend_state="—", frontend_route="/users (patrón) + resto",
        frontend_component="UsersPage (+ resto pendiente R-150)", frontend_repo_state="PARTIAL", nav_entry="—",
        discoverable="—", deployed="ABSENT", runtime_visible="no (persiste Promise.all + catch{})", runtime_functional="no",
        persistence="—", refresh="—", relogin="—", negative_auth="—", e2e="—", screenshot="—",
        network_evidence="bundle desplegado con el patrón antiguo", existing_finding="R-99 · R-150",
        primary_product_status="DEPLOYMENT_STALE",
        secondary_gaps="el patrón corregido (09-08) no está desplegado; R-150 cubre el resto de páginas", severity="P2",
        root_cause="artefacto congelado", owner_decision="—", remediation_dependency="R-99 · R-150",
        proposed_remediation_group="G7-deploy-parity", evidence_ref="EVIDENCE §21"),
]

def main():
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "MASTER_FRONTEND_RUNTIME_GAP_MATRIX.csv")
    with open(out, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        writer.writerow(COLUMNS)
        for r in ROWS:
            writer.writerow(r)
    # invariantes
    classified = [r for r in ROWS if r[COLUMNS.index("primary_product_status")] != B]
    blocked = [r for r in ROWS if r[COLUMNS.index("primary_product_status")] == B]
    from collections import Counter
    counts = Counter(r[COLUMNS.index("primary_product_status")] for r in classified)
    print(f"filas totales .......... {len(ROWS)}")
    print(f"clasificadas ........... {len(classified)}")
    print(f"bloqueadas (auth) ...... {len(blocked)}")
    for k, v in sorted(counts.items()):
        print(f"  {k}: {v}")
    total = sum(counts.values())
    assert total == len(classified), "invariante roto"
    print(f"invariante TOTAL = suma de estados: {total} == {len(classified)} ✓")
    print(f"escrito: {out}")

if __name__ == "__main__":
    main()
