"""add_sap_integration_tables

Revision ID: 397a95b7e826
Revises: e4c4cc5420de
Create Date: 2026-06-23 02:13:17.544813
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '397a95b7e826'
down_revision: Union[str, None] = 'e4c4cc5420de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sync_job_id', sa.Integer(), nullable=True),
    sa.Column('consolidated_movement_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('payload_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PREPARED', 'SENDING', 'CONFIRMED', 'FAILED', 'RETRYING', name='payloadstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sap_document_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_payloads_company_id'), 'sap_payloads', ['company_id'], unique=False)
    op.create_index(op.f('ix_sap_payloads_idempotency_key'), 'sap_payloads', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_sap_payloads_sync_job_id'), 'sap_payloads', ['sync_job_id'], unique=False)
    op.create_table('sap_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.Enum('PURCHASE_ORDER', 'TRANSFER_ORDER', 'MATERIAL', 'VENDOR', 'PLANT', 'STORAGE_LOCATION', 'COST_CENTER', 'SAP_BATCH', 'OTHER', name='sapreferencetype'), nullable=False),
    sa.Column('sap_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('imported_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_references_company_id'), 'sap_references', ['company_id'], unique=False)
    op.create_index(op.f('ix_sap_references_ref_type'), 'sap_references', ['ref_type'], unique=False)
    op.create_index(op.f('ix_sap_references_sap_code'), 'sap_references', ['sap_code'], unique=False)
    op.create_table('sap_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('sap_document_id', sa.String(length=100), nullable=True),
    sa.Column('sap_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payload_id'], ['sap_payloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_responses_payload_id'), 'sap_responses', ['payload_id'], unique=False)
    op.create_table('sap_sync_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('IMPORT', 'EXPORT', name='syncdirection'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('initiated_by_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_sync_jobs_company_id'), 'sap_sync_jobs', ['company_id'], unique=False)
    op.create_table('consolidated_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('sap_reference', sa.String(length=100), nullable=True),
    sa.Column('consolidated_by_id', sa.Integer(), nullable=False),
    sa.Column('sap_payload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['consolidated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consolidated_movements_company_id'), 'consolidated_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_consolidated_movements_lot_id'), 'consolidated_movements', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consolidated_movements_lot_id'), table_name='consolidated_movements')
    op.drop_index(op.f('ix_consolidated_movements_company_id'), table_name='consolidated_movements')
    op.drop_table('consolidated_movements')
    op.drop_index(op.f('ix_sap_sync_jobs_company_id'), table_name='sap_sync_jobs')
    op.drop_table('sap_sync_jobs')
    op.drop_index(op.f('ix_sap_responses_payload_id'), table_name='sap_responses')
    op.drop_table('sap_responses')
    op.drop_index(op.f('ix_sap_references_sap_code'), table_name='sap_references')
    op.drop_index(op.f('ix_sap_references_ref_type'), table_name='sap_references')
    op.drop_index(op.f('ix_sap_references_company_id'), table_name='sap_references')
    op.drop_table('sap_references')
    op.drop_index(op.f('ix_sap_payloads_sync_job_id'), table_name='sap_payloads')
    op.drop_index(op.f('ix_sap_payloads_idempotency_key'), table_name='sap_payloads')
    op.drop_index(op.f('ix_sap_payloads_company_id'), table_name='sap_payloads')
    op.drop_table('sap_payloads')
    # ### end Alembic commands ###
