"""add_egg_storage_and_weekly_tracking_fields

Revision ID: 4396a2b7e7d6
Revises: 748464484981
Create Date: 2026-06-23 04:55:55.054249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4396a2b7e7d6'
down_revision: Union[str, None] = '748464484981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egg_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('eggs_received', sa.Integer(), nullable=False),
    sa.Column('storage_temp_c', sa.Float(), nullable=True),
    sa.Column('storage_humidity_pct', sa.Float(), nullable=True),
    sa.Column('storage_start_date', sa.Date(), nullable=True),
    sa.Column('storage_end_date', sa.Date(), nullable=True),
    sa.Column('transport_temp_c', sa.Float(), nullable=True),
    sa.Column('transport_duration_min', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egg_storage_event_id'), 'egg_storage', ['event_id'], unique=False)
    op.create_index(op.f('ix_egg_storage_lot_id'), 'egg_storage', ['lot_id'], unique=False)
    op.add_column('bird_movements', sa.Column('week_number', sa.Integer(), nullable=True))
    op.add_column('egg_movements', sa.Column('storage_start_date', sa.Date(), nullable=True))
    op.add_column('egg_movements', sa.Column('storage_temp_c', sa.Float(), nullable=True))
    op.add_column('egg_movements', sa.Column('storage_humidity_pct', sa.Float(), nullable=True))
    op.add_column('feed_movements', sa.Column('sacks_count', sa.Integer(), nullable=True))
    op.add_column('feed_movements', sa.Column('week_number', sa.Integer(), nullable=True))
    op.alter_column('users', 'view_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'web'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'view_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'web'::character varying"))
    op.drop_column('feed_movements', 'week_number')
    op.drop_column('feed_movements', 'sacks_count')
    op.drop_column('egg_movements', 'storage_humidity_pct')
    op.drop_column('egg_movements', 'storage_temp_c')
    op.drop_column('egg_movements', 'storage_start_date')
    op.drop_column('bird_movements', 'week_number')
    op.drop_index(op.f('ix_egg_storage_lot_id'), table_name='egg_storage')
    op.drop_index(op.f('ix_egg_storage_event_id'), table_name='egg_storage')
    op.drop_table('egg_storage')
    # ### end Alembic commands ###
