"""add_company_id_indexes_to_master_tables

Revision ID: 4982c3092c14
Revises: d2e3f4a5b6c7
Create Date: 2026-06-26 23:35:17.272245
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4982c3092c14'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chick_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_correction_types_company_id'), 'correction_types', ['company_id'], unique=False)
    op.create_index(op.f('ix_cull_causes_company_id'), 'cull_causes', ['company_id'], unique=False)
    op.alter_column('egg_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_farms_company_id'), 'farms', ['company_id'], unique=False)
    op.create_index(op.f('ix_feed_types_company_id'), 'feed_types', ['company_id'], unique=False)
    op.create_index(op.f('ix_genetic_lines_company_id'), 'genetic_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_hatcheries_company_id'), 'hatcheries', ['company_id'], unique=False)
    op.drop_constraint(op.f('fk_inspection_detail_house'), 'inspection_details', type_='foreignkey')
    op.create_foreign_key(None, 'inspection_details', 'houses', ['house_id'], ['id'])
    op.create_index(op.f('ix_lots_company_id'), 'lots', ['company_id'], unique=False)
    op.create_index(op.f('ix_medications_company_id'), 'medications', ['company_id'], unique=False)
    op.create_index(op.f('ix_mortality_causes_company_id'), 'mortality_causes', ['company_id'], unique=False)
    op.create_index(op.f('ix_processing_plants_company_id'), 'processing_plants', ['company_id'], unique=False)
    op.create_index(op.f('ix_rejection_reasons_company_id'), 'rejection_reasons', ['company_id'], unique=False)
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_index(op.f('ix_transports_company_id'), 'transports', ['company_id'], unique=False)
    op.create_index(op.f('ix_vaccines_company_id'), 'vaccines', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccines_company_id'), table_name='vaccines')
    op.drop_index(op.f('ix_transports_company_id'), table_name='transports')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_index(op.f('ix_rejection_reasons_company_id'), table_name='rejection_reasons')
    op.drop_index(op.f('ix_processing_plants_company_id'), table_name='processing_plants')
    op.drop_index(op.f('ix_mortality_causes_company_id'), table_name='mortality_causes')
    op.drop_index(op.f('ix_medications_company_id'), table_name='medications')
    op.drop_index(op.f('ix_lots_company_id'), table_name='lots')
    op.drop_constraint(None, 'inspection_details', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inspection_detail_house'), 'inspection_details', 'houses', ['house_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_hatcheries_company_id'), table_name='hatcheries')
    op.drop_index(op.f('ix_genetic_lines_company_id'), table_name='genetic_lines')
    op.drop_index(op.f('ix_feed_types_company_id'), table_name='feed_types')
    op.drop_index(op.f('ix_farms_company_id'), table_name='farms')
    op.alter_column('egg_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cull_causes_company_id'), table_name='cull_causes')
    op.drop_index(op.f('ix_correction_types_company_id'), table_name='correction_types')
    op.alter_column('chick_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
