"""add_view_type_to_users

Revision ID: 748464484981
Revises: ee30bd1aa374
Create Date: 2026-06-23 04:14:31.765765
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '748464484981'
down_revision: Union[str, None] = 'ee30bd1aa374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('view_type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'view_type')
    # ### end Alembic commands ###
