"""add_operational_events

Revision ID: 7922512fdef4
Revises: ad12f3f3ad19
Create Date: 2026-06-23 01:46:14.718579
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7922512fdef4'
down_revision: Union[str, None] = 'ad12f3f3ad19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('BIRD_RECEPTION', 'BIRD_DISTRIBUTION', 'BIRD_TRANSFER', 'BIRD_EXIT', 'FEED_REGISTRATION', 'WEIGHT_RECORDING', 'MORTALITY_RECORDING', 'CULL_RECORDING', 'VACCINATION', 'MEDICATION', 'FARM_INSPECTION', 'TRANSPORT_INSPECTION', 'HATCHERY_INSPECTION', 'EGG_COLLECTION', 'EGG_CLASSIFICATION', 'EGG_DISPATCH', 'EGG_RECEPTION_HATCHERY', 'INCUBATION_LOAD', 'OVOSCOPY', 'TRANSFER_TO_HATCHER', 'BIRTH_REGISTRATION', 'CHICK_DISPATCH', 'LOT_CLOSURE', 'GRANDPARENT_IMPORT', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTERED', 'PENDING_REVIEW', 'IN_REVIEW', 'RETURNED', 'CORRECTED', 'APPROVED', 'REJECTED', 'CONSOLIDATED', 'SENT_TO_SAP', 'SAP_CONFIRMED', 'SAP_ERROR', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('sap_document_ref', sa.String(length=100), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_events_company_id'), 'operational_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_operational_events_event_type'), 'operational_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_operational_events_lot_id'), 'operational_events', ['lot_id'], unique=False)
    op.create_table('bird_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_weight', sa.Float(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('source_house_id', sa.Integer(), nullable=True),
    sa.Column('target_house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['source_house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['target_house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bird_movements_event_id'), 'bird_movements', ['event_id'], unique=False)
    op.create_table('egg_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('egg_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_weight', sa.Float(), nullable=True),
    sa.Column('classification_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egg_movements_event_id'), 'egg_movements', ['event_id'], unique=False)
    op.create_table('feed_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('sap_order_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_movements_event_id'), 'feed_movements', ['event_id'], unique=False)
    op.create_table('hatchery_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('hatchery_id', sa.Integer(), nullable=True),
    sa.Column('incubator_id', sa.Integer(), nullable=True),
    sa.Column('hatcher_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('co2', sa.Float(), nullable=True),
    sa.Column('turning', sa.Boolean(), nullable=True),
    sa.Column('quantity_loaded', sa.Integer(), nullable=True),
    sa.Column('quantity_transferred', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['hatcher_id'], ['hatchers.id'], ),
    sa.ForeignKeyConstraint(['hatchery_id'], ['hatcheries.id'], ),
    sa.ForeignKeyConstraint(['incubator_id'], ['incubators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hatchery_params_event_id'), 'hatchery_params', ['event_id'], unique=False)
    op.create_table('inspection_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_details_event_id'), 'inspection_details', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_details_event_id'), table_name='inspection_details')
    op.drop_table('inspection_details')
    op.drop_index(op.f('ix_hatchery_params_event_id'), table_name='hatchery_params')
    op.drop_table('hatchery_params')
    op.drop_index(op.f('ix_feed_movements_event_id'), table_name='feed_movements')
    op.drop_table('feed_movements')
    op.drop_index(op.f('ix_egg_movements_event_id'), table_name='egg_movements')
    op.drop_table('egg_movements')
    op.drop_index(op.f('ix_bird_movements_event_id'), table_name='bird_movements')
    op.drop_table('bird_movements')
    op.drop_index(op.f('ix_operational_events_lot_id'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_event_type'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_company_id'), table_name='operational_events')
    op.drop_table('operational_events')
    # ### end Alembic commands ###
