"""add_lot_phases_and_opening_balances

Revision ID: ad12f3f3ad19
Revises: b53bbe02a476
Create Date: 2026-06-23 01:34:52.414281
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad12f3f3ad19'
down_revision: Union[str, None] = 'b53bbe02a476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot_phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_population_male', sa.Integer(), nullable=False),
    sa.Column('start_population_female', sa.Integer(), nullable=False),
    sa.Column('start_weight_avg', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['productive_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_phases_lot_id'), 'lot_phases', ['lot_id'], unique=False)
    op.create_table('opening_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('activation_date', sa.Date(), nullable=False),
    sa.Column('phase_at_activation_id', sa.Integer(), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('initial_male_count', sa.Integer(), nullable=False),
    sa.Column('initial_female_count', sa.Integer(), nullable=False),
    sa.Column('accumulated_mortality_male', sa.Integer(), nullable=False),
    sa.Column('accumulated_mortality_female', sa.Integer(), nullable=False),
    sa.Column('accumulated_culls_male', sa.Integer(), nullable=False),
    sa.Column('accumulated_culls_female', sa.Integer(), nullable=False),
    sa.Column('accumulated_feed_kg', sa.Float(), nullable=True),
    sa.Column('current_avg_weight', sa.Float(), nullable=True),
    sa.Column('accumulated_egg_production', sa.Integer(), nullable=True),
    sa.Column('accumulated_eggs_to_hatchery', sa.Integer(), nullable=True),
    sa.Column('accumulated_chicks_hatched', sa.Integer(), nullable=True),
    sa.Column('accumulated_broiler_received', sa.Integer(), nullable=True),
    sa.Column('is_manual_activation', sa.Boolean(), nullable=False),
    sa.Column('activated_by_id', sa.Integer(), nullable=False),
    sa.Column('activation_reason', sa.Text(), nullable=False),
    sa.Column('support_document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['phase_at_activation_id'], ['productive_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_balances_lot_id'), 'opening_balances', ['lot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opening_balances_lot_id'), table_name='opening_balances')
    op.drop_table('opening_balances')
    op.drop_index(op.f('ix_lot_phases_lot_id'), table_name='lot_phases')
    op.drop_table('lot_phases')
    # ### end Alembic commands ###
