"""add_evidences_alerts_reversals_and_sap

Revision ID: bfcc893f581a
Revises: 4396a2b7e7d6
Create Date: 2026-06-23 07:14:32.788728
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bfcc893f581a'
down_revision: Union[str, None] = '4396a2b7e7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_company_id'), 'evidences', ['company_id'], unique=False)
    op.create_index(op.f('ix_evidences_event_id'), 'evidences', ['event_id'], unique=False)
    op.create_table('operational_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_alerts_company_id'), 'operational_alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_lot_id'), 'operational_alerts', ['lot_id'], unique=False)
    op.create_table('reversals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_event_id', sa.Integer(), nullable=False),
    sa.Column('reversal_event_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reversed_by_id', sa.Integer(), nullable=False),
    sa.Column('original_data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reversal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['original_event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['reversal_event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reversals_company_id'), 'reversals', ['company_id'], unique=False)
    op.create_index(op.f('ix_reversals_original_event_id'), 'reversals', ['original_event_id'], unique=False)
    op.add_column('sap_payloads', sa.Column('external_transaction_id', sa.String(length=120), nullable=True))
    op.add_column('sap_payloads', sa.Column('source_system', sa.String(length=50), nullable=True))
    op.add_column('sap_payloads', sa.Column('sap_reference_item', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_sap_payloads_external_transaction_id'), 'sap_payloads', ['external_transaction_id'], unique=True)
    op.add_column('sap_references', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('sap_references', sa.Column('unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sap_references', 'unit')
    op.drop_column('sap_references', 'quantity')
    op.drop_index(op.f('ix_sap_payloads_external_transaction_id'), table_name='sap_payloads')
    op.drop_column('sap_payloads', 'sap_reference_item')
    op.drop_column('sap_payloads', 'source_system')
    op.drop_column('sap_payloads', 'external_transaction_id')
    op.drop_index(op.f('ix_reversals_original_event_id'), table_name='reversals')
    op.drop_index(op.f('ix_reversals_company_id'), table_name='reversals')
    op.drop_table('reversals')
    op.drop_index(op.f('ix_operational_alerts_lot_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_company_id'), table_name='operational_alerts')
    op.drop_table('operational_alerts')
    op.drop_index(op.f('ix_evidences_event_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_company_id'), table_name='evidences')
    op.drop_table('evidences')
    # ### end Alembic commands ###
