"""add_review_and_corrections

Revision ID: e4c4cc5420de
Revises: 7922512fdef4
Create Date: 2026-06-23 01:57:30.734561
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4c4cc5420de'
down_revision: Union[str, None] = '7922512fdef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('can_correct', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_reject', sa.Boolean(), nullable=False),
    sa.Column('require_segregation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_steps_company_id'), 'approval_steps', ['company_id'], unique=False)
    op.create_table('review_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='batchstatus'), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('approved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_batches_company_id'), 'review_batches', ['company_id'], unique=False)
    op.create_table('approval_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('STARTED_REVIEW', 'RETURNED', 'CORRECTED', 'APPROVED', 'REJECTED', name='actiontype'), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['review_batches.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['approval_steps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_actions_batch_id'), 'approval_actions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_approval_actions_event_id'), 'approval_actions', ['event_id'], unique=False)
    op.create_table('correction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_by_id', sa.Integer(), nullable=False),
    sa.Column('correction_type_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['correction_type_id'], ['correction_types.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_logs_event_id'), 'correction_logs', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_logs_event_id'), table_name='correction_logs')
    op.drop_table('correction_logs')
    op.drop_index(op.f('ix_approval_actions_event_id'), table_name='approval_actions')
    op.drop_index(op.f('ix_approval_actions_batch_id'), table_name='approval_actions')
    op.drop_table('approval_actions')
    op.drop_index(op.f('ix_review_batches_company_id'), table_name='review_batches')
    op.drop_table('review_batches')
    op.drop_index(op.f('ix_approval_steps_company_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    # ### end Alembic commands ###
